### ISSUE TITLE
Unable to send request with attachments

### ISSUE THREAD

**Issue by steventranjs** [strongloop/loopback-connector-rest#106]
# Description/Steps to reproduce
1. I have this template
```
{
        template: {
          method: 'POST',
          url: 'http://localhost/some-ftp-server',
          headers: {
            accepts: 'multipart/form-data',
            'content-type': 'multipart/form-data'
          },
          attachments: [{ field: 'file', path: '/tmp/file.json' }]
        },
        functions: {
          sendFileToserver: []
        }
}
```
2. Execute `sendFileToserver` will results in below error:
```
TypeError: Cannot read property 'form' of undefined
    at RequestBuilder.invoke (/Users/.../node_modules/loopback-connector-rest/lib/rest-builder.js:551:17)
    at Function.writeHdfsFile (/Users/.../node_modules/loopback-connector-rest/lib/rest-builder.js:439:17)
```
The issue is because variable **r** is NOT defined anywhere before line 551 in this file: https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-builder.js (Line 551)

# Expected result
- Should be able to send the attachment.

**Comment by ketansp** [comment]
This issue should be re-opened
