### ISSUE TITLE
CI failed on "mix in custom methods" test

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-rest#108]
CI failed on the following test with the error stack below:
```
1) REST connector custom operations should mix in custom methods for all functions:
     Uncaught TypeError: Cannot read property 'formatted_address' of undefined
      at test/rest-adapter-custom.test.js:170:38
      at callback (lib/rest-builder.js:545:16)
      at node_modules/loopback-datasource-juggler/lib/observer.js:250:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
      at RestConnector.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
      at RestConnector.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
      at cbForWork (node_modules/loopback-datasource-juggler/lib/observer.js:240:14)
      at Request._callback (lib/rest-builder.js:596:7)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:923:12)

```

**Comment by dhmlau** [comment]
seems like it's no longer a problem. closing it
