### ISSUE TITLE
lookback-connnector-rest cannot pass CA attribute for self-signed certification

### ISSUE THREAD

**Issue by yangguoyk2015** [strongloop/loopback-connector-rest#113]
# Description/Steps to reproduce
We have internal https application, which are https API server with self-signed certificate. When try to read the CA file and pass it for https, it always failed ,but the prototype `request` model work well. 

Here is my template config for the https method in rest-connector:
```
{
        "template": {
          "method": "GET",
          "url": "https://localhost:3000/api/{p}",
          "headers": {
            "accepts": "application/json",
            "content-type": "application/json"
          },
          "options": {
            "headers": {
              "accept": "application/json",
              "content-type": "application/json"
            },
            // agentOptions: {
            //   "ca": fs.readFileSync('private/certificate.pem')
            // }
            "ca": ca2
          },
          "body": "{body}"
        },
        "functions": {
          "query": [
            "p",
            "body"
          ]
        }
      }
```
The error message say below:
```
Unhandled error for request GET /rests/Users: TypeError: Method Uint8Array.length called on incompatible receiver [object Object]
    at Buffer.get length (native)
    at Buffer.toString (buffer.js:373:36)
    at Request.getNewAgent (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/request/request.js:639:25)
    at Request.init (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/request/request.js:487:37)
    at new Request (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/request/request.js:128:8)
    at request (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/request/index.js:53:10)
    at RequestBuilder.request.defaults.self [as request] (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/request/index.js:100:12)
    at work (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-connector-rest/lib/rest-builder.js:594:10)
    at /Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-datasource-juggler/lib/observer.js:259:9
    at doNotify (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at RestConnector.ObserverMixin._notifyBaseObservers (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at RestConnector.ObserverMixin.notifyObserversOf (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at RestConnector.ObserverMixin.notifyObserversAround (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-datasource-juggler/lib/observer.js:228:15)
    at RequestBuilder._request (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-connector-rest/lib/rest-builder.js:599:13)
    at RequestBuilder.invoke (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-connector-rest/lib/rest-builder.js:557:16)
    at DataSource.RequestBuilder.operation [as query] (/Users/kaishen/Documents/Confidential/gitlab/sbux/lookpback/loopback-connect-rest-sample/node_modules/loopback-connector-rest/lib/rest-builder.js:439:17)

```

when debug into request module, it says following error:
![image](https://user-images.githubusercontent.com/12314244/32401516-e323c682-c0dd-11e7-8085-b632a1080f67.png)

while everything work well using the native `request` module like below:
```
var fs = require('fs')
  , path = require('path')
  , certFile = path.resolve(__dirname, 'ssl/client.crt')
  , keyFile = path.resolve(__dirname, 'ssl/client.key')
  , request = require('request');

var ca2 = fs.readFileSync('../private/certificate.pem');
console.log(ca2)

var options = {
  url: 'https://localhost:3000/api/Users',
  ca: fs.readFileSync('../private/certificate.pem')
};

request(options, function (err, data) {
  if(err)
    console.log(err)
  else
    console.log(data.body)
});
``` 

BTW, i am using another [loopback-example-ssl](https://github.com/strongloop/loopback-example-ssl) to build the https server.

# Link to reproduction sandbox

NA

# Expected result

Expect the this module configuration should have the same result as the `request` module, as the [documentation](https://github.com/strongloop/loopback-connector-rest#configure-options-for-request)

# Additional information

- [configure-options-for-request](https://github.com/strongloop/loopback-connector-rest#configure-options-for-request)
- [request#tlsssl-protocol](https://www.npmjs.com/package/request#tlsssl-protocol)
- [loopback-example-ssl](https://github.com/strongloop/loopback-example-ssl)

**Comment by yangguoyk2015** [comment]
Finally, I found this is due to my loopback-root version is `"loopback-boot": "^2.6.5"`, which is still pointing to  `"lodash": "^3.6.0"`,  while that version of `lodash` cannot deepClone buffer value properly.

https://github.com/strongloop/loopback-boot/blob/5060032d265bd457c14ea2510ecd0d017a7a2f1b/lib/config-loader.js#L130

Do we have any solution to fix such issue in loopback 2.x?
