### ISSUE TITLE
Getting Error while creating Rest Service Datasource

### ISSUE THREAD

**Issue by WeirdThinker15** [strongloop/loopback-connector-rest#51]
`slc loopback:datasource proxyAPI
? Enter the data-source name: proxyAPI
? Select the connector for proxyAPI: REST services (supported by StrongLoop)
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'facetName' of undefined
    at exports._extend (util.js:777:21)
    at module.exports.yeoman.generators.Base.extend.dataSource (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:169:18)
    at /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by niwsa** [comment]
I am also getting the same error when trying to add a rest api source.
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'facetName' of undefined
    at exports._extend (util.js:770:21)
    at module.exports.yeoman.generators.Base.extend.dataSource (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:169:18)
    at /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by raymondfeng** [comment]
I can reproduce the problem. Will try to fix it.

**Comment by raymondfeng** [comment]
Released in generator-loopback@1.16.3. Please run `npm i -g strongloop` again.

**Comment by niwsa** [comment]
I am still facing the issue even after upgrading
$ npm -g info generator-loopback version
1.17.2
$ npm -g info strongloop version
6.0.0

**Comment by raymondfeng** [comment]
You cannot run npm -g generator-loopback. It has to be installed as part of npm i -g strongloop.

**Comment by niwsa** [comment]
But its not working.
$ sudo npm i -g strongloop 
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/slc -> /usr/local/lib/node_modules/strongloop/bin/slc.js
/usr/local/bin/lb-ng -> /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng
/usr/local/lib
`-- strongloop@6.0.0 
  `-- generator-loopback@1.17.2 
    `-- loopback-workspace@3.24.1 
$ slc loopback:datasource
? Enter the data-source name: DominoAPI
? Select the connector for DominoAPI: REST services (supported by StrongLoop)
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'facetName' of undefined
    at exports._extend (util.js:770:21)
    at module.exports.yeoman.generators.Base.extend.dataSource (/usr/local/lib/node_modules/generator-loopback/datasource/index.js:169:18)
    at /usr/local/lib/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by raymondfeng** [comment]
Can you run `npm -g uninstall generator-loopback` to get rid of the offending global module? From your stacktrace, `/usr/local/lib/node_modules/generator-loopback/datasource/index.js` is used instead of the one from `strongloop`.

I just confirmed latest version of `strongloop` works for me.

**Comment by niwsa** [comment]
@raymondfeng Thanks a lot its working :)
