### ISSUE TITLE
Error when tried execute update

### ISSUE THREAD

**Issue by brilvio** [strongloop/loopback-connector-rest#87]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I am trying to connect to another loopback server and update a model, but I having a error when trying to execute this code:
```javascript
var ds = app.loopback.createDataSource({
    connector: require("loopback-connector-rest"),
    debug: false,
    baseURL: 'http://localhost:3000/api'
});

var Emp = ds.createModel('empresa', {
    id: Number,
    idFilial: Number,
    cnpj: String,
    nome: String,
    remoteHook: String,
    email: String,
    password: String
});

Emp.update(new Emp({
    id: empresa.id,
    idFilial: dados.idFilial,
    cnpj: dados.cnpj,
    nome: dados.nomefilial,
    remoteHook: ctx.instance.remoteHook,
    email: ctx.instance.email,
    password: ctx.instance.password
}), function (err, empresa) {
    if (err) next(err);
});
```
This is the error: 
```bash
xpert@PRG1:~/projetos_git/iGas/client$ DEBUG=loopback:connector:rest node .
  loopback:connector:rest RestConnector:settings +0ms { name: 'Rest',
  baseURL: 'http://localhost:3000/api',
  crud: true,
  connector: 'rest',
  debug: false }
  loopback:connector:rest RestConnector:this._settings +4ms { name: 'Rest',
  baseURL: 'http://localhost:3000/api',
  crud: true,
  debug: false }
Web server listening at: http://0.0.0.0:3030
Browse your REST API at http://0.0.0.0:3030/explorer
  loopback:connector:rest Request: {"method":"GET","uri":"http://localhost:3000/api/empresas","json":true,"qs":{"access_token":"Q2h1fUNUeFKcmdwyQifQzoBUBmHuPKhDH6xEPHQlD0YPCP09uJDteHD3172Go8Rg","filter":{"where":{"idFilial":4727}},"limit":1,"offset":0,"skip":0}} +2s
  loopback:connector:rest RestConnector:settings +30ms { connector: 
   { [Function: RequestBuilder]
     acl: [Function],
     bind: [Function],
     checkout: [Function],
     connect: [Function],
     copy: [Function],
     del: [Function],
     get: [Function],
     head: [Function],
     link: [Function],
     lock: [Function],
     'm-search': [Function],
     merge: [Function],
     mkactivity: [Function],
     mkcalendar: [Function],
     mkcol: [Function],
     move: [Function],
     notify: [Function],
     options: [Function],
     patch: [Function],
     post: [Function],
     propfind: [Function],
     proppatch: [Function],
     purge: [Function],
     put: [Function],
     rebind: [Function],
     report: [Function],
     search: [Function],
     subscribe: [Function],
     trace: [Function],
     unbind: [Function],
     unlink: [Function],
     unlock: [Function],
     unsubscribe: [Function],
     fromJSON: [Function],
     compile: [Function],
     resource: [Function],
     RestConnector: [Function: RestConnector],
     initialize: [Function: initializeDataSource] },
  debug: false,
  baseURL: 'http://localhost:3000/api' }
  loopback:connector:rest RestConnector:this._settings +1ms { debug: false, baseURL: 'http://localhost:3000/api' }
{ AssertionError: update() must be implemented by the connector
    at Function.DataAccessObject.update.DataAccessObject.updateAll (/home/xpert/projetos_git/iGas/client/node_modules/loopback-datasource-juggler/lib/dao.js:2515:3)
    at DataSource.onConnected (/home/xpert/projetos_git/iGas/client/node_modules/loopback-datasource-juggler/lib/datasource.js:2095:14)
    at DataSource.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DataSource.emit (events.js:185:7)
    at DataSource.postInit (/home/xpert/projetos_git/iGas/client/node_modules/loopback-datasource-juggler/lib/datasource.js:327:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'update() must be implemented by the connector',
  generatedMessage: false }
```
### Expected result
Excute the update without any problem.

### Actual result (if bug)
Error on executing the update see above.

### Additional information (Node.js version, LoopBack version, etc)
The same error happens when I tried to use the https://github.com/strongloop/loopback-connector-remote 

```bash
xpert@PRG1:~/projetos_git/iGas/client$ node --version
v6.9.2
```
```bash
xpert@PRG1:~/projetos_git/iGas/client$ slc --version
strongloop v6.0.3 (node v6.9.2)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.0 (1767f27)
├── generator-loopback@1.24.4 (0c6b9c3)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
``` 
```json
"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^1.0.1",
    "loopback-datasource-juggler": "^2.39.0",
    "loopback": "^2.22.0"
  }
```

**Comment by ksekhar** [comment]
Not really a work around but when I do a PATH to the path /resource/:id instead of a PUT it worked.
Hope this is useful to someone who gets here.
